### ISSUE TITLE
Level of details available in ACM

### ISSUE THREAD

**Issue by SimonDelord** [sdminonne/sre-tools#1]
One general comment is that it is difficult to get access to how ACM behaves under the hood.
This is just a wish list of information that would be great to have more details on:

- detailed list of steps and actions for ACM when creating a cluster
- detailed list of steps and action for ACM and remote cluster when importing a cluster

- detailed list of steps and actions for ACM & managed cluster(s) when deploying an application
- same as above for updates to an application 
- detailed list of steps and actions for ACM & managed cluster(s) when deploying a policy
- same as above for updates to policies
(S. Delord)

**Comment by sdminonne** [comment]
@SimonDelord first of all, thanks for opening this.  
This site is under construction and should not be considered a replacement for official DOC. We're going to document more the ACM internals.

**Comment by sdminonne** [comment]
@cdoan1 FYI

**Comment by sdminonne** [comment]
@SimonDelord please see: https://github.com/open-cluster-management/sre-tools/issues/1
Closing this.
Thanks!
