### ISSUE TITLE
example of advanced use cases for ACM

### ISSUE THREAD

**Issue by SimonDelord** [sdminonne/sre-tools#2]
Here's an example of advanced use cases for ACM where we may require some flexibility on label constructs 
1/ deployment of hybrid applications (requires support for OCP Virtualisation (virtualiZation)) - https://youtu.be/kqCv-xBjhGc
2/ deployment of VNFs on Edge cluster (requires support for OCP Virtualisation) - https://youtu.be/ghgNS-nkv-E
3/ deployment of operators / operators control planes / apps using those operators - example here of Service-mesh https://youtu.be/2Xwe1zo1Y7o
4/ app migrations and portability between clusters (for example is it feasible to migrate an app from a specific cluster to another one - e.g does this app have all the relevant dependencies to be deployed/migrated onto a target cluster) - a couple of videos showing migration of "hello worlds"that can be migrated or cannot - but would be interesting to define rules for "real apps" - https://youtu.be/fLKqccn5vV0 (from EKS to OCP)
5/ Definition of cluster sizes via ACM (e.g control Machine Autoscalers + cluster-autoscaler) as a way of enforcing consistency (E.g rules) for them - https://youtu.be/__srW3Fa6kk

6/ one example of CICD pipeline using ACM with Tekton and OCP - details on https://github.com/SimonDelord/tekton and associated video - https://youtu.be/0XCGMn9-d3Y

**Comment by SimonDelord** [comment]
sorry all git repos are available under https://github.com/SimonDelord/ACM-Templates

**Comment by sdminonne** [comment]
@SimonDelord thanks for all this! @cdoan1  FYI

**Comment by sdminonne** [comment]
@SimonDelord I'm adding here what you mentioned in PM in our chat: https://github.com/SimonDelord/ACM-Workshop 
Thanks for this!

**Comment by sdminonne** [comment]
Closing this in favor of https://github.com/open-cluster-management/sre-tools/issues/2
