### ISSUE TITLE
After backup and restore procedure is tested some ACM PODs keep crashing

### ISSUE THREAD

**Issue by sdminonne** [sdminonne/sre-tools#3]
multiclusterhub-operator-598d95d5f8-68kr7                         0/1     CrashLoopBackOff   5          6m8s

With this log:

{"level":"info","ts":1620133965.8486245,"logger":"controller_multiclusterhub","msg":"Helmrelease has no owner reference!","Name":"topology-e2bda"}
E0504 13:12:45.861634       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 1879 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x209f8c0, 0xc0018d4520)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:48 +0x82
panic(0x209f8c0, 0xc0018d4520)
	/opt/rh/go-toolset-1.13/root/usr/lib/go-toolset-1.13-golang/src/runtime/panic.go:679 +0x1b2
github.com/open-cluster-management/multicloudhub-operator/pkg/controller/multiclusterhub.getAppSubOwnedHelmReleases(0xc0000fd700, 0x16, 0x20, 0xc0001ed1e0, 0xb, 0xb, 0x20, 0x0, 0x0)
	/remote-source/app/pkg/controller/multiclusterhub/common.go:533 +0x298
github.com/open-cluster-management/multicloudhub-operator/pkg/controller/multiclusterhub.(*ReconcileMultiClusterHub).Reconcile(0xc0004a7900, 0xc000746640, 0x17, 0xc0009d4490, 0xf, 0xc000070c00, 0x0, 0x0, 0x0)
	/remote-source/app/pkg/controller/multiclusterhub/multiclusterhub_controller.go:296 +0xb67
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000162b40, 0x1ffc360, 0xc000509920, 0xc0036ab800)
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000162b40, 0x1b84800)
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000162b40)
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006f49e0)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006f49e0, 0x23ee540, 0xc000628870, 0xc00051bf01, 0xc0005d2a20)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006f49e0, 0x3b9aca00, 0x0, 0x1, 0xc0005d2a20)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006f49e0, 0x3b9aca00, 0xc0005d2a20)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1879 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:55 +0x105
panic(0x209f8c0, 0xc0018d4520)
	/opt/rh/go-toolset-1.13/root/usr/lib/go-toolset-1.13-golang/src/runtime/panic.go:679 +0x1b2
github.com/open-cluster-management/multicloudhub-operator/pkg/controller/multiclusterhub.getAppSubOwnedHelmReleases(0xc0000fd700, 0x16, 0x20, 0xc0001ed1e0, 0xb, 0xb, 0x20, 0x0, 0x0)
	/remote-source/app/pkg/controller/multiclusterhub/common.go:533 +0x298
github.com/open-cluster-management/multicloudhub-operator/pkg/controller/multiclusterhub.(*ReconcileMultiClusterHub).Reconcile(0xc0004a7900, 0xc000746640, 0x17, 0xc0009d4490, 0xf, 0xc000070c00, 0x0, 0x0, 0x0)
	/remote-source/app/pkg/controller/multiclusterhub/multiclusterhub_controller.go:296 +0xb67
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000162b40, 0x1ffc360, 0xc000509920, 0xc0036ab800)
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000162b40, 0x1b84800)
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000162b40)
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0006f49e0)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006f49e0, 0x23ee540, 0xc000628870, 0xc00051bf01, 0xc0005d2a20)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006f49e0, 0x3b9aca00, 0x0, 0x1, 0xc0005d2a20)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006f49e0, 0x3b9aca00, 0xc0005d2a20)
	/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x328

**Comment by cdoan1** [comment]
nice find!
